zookeeper:
        image: 'jplock/zookeeper:3.4.9'
        ports:
          - '2181:2181'
kafka:
        image: 'ches/kafka:0.10.2.0'
        links:
          - zookeeper:zookeeper
        ports:
          - "9092:9092"
